---
name: 🕵️ Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.set-build-matrix.outputs.build_matrix }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.3.1

      - id: set-build-matrix
        run: echo "build_matrix=$(bash matrix.sh build)" >> $GITHUB_OUTPUT

  scan_ci_container:
    name: 'Scan CI container'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.build_matrix) }}
    needs: setup-matrix
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CI container
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: 'ci/r10k-webhook:${{ github.sha }}'
          file: Containerfile
          build-args: |
            R10K_VERSION=${{ matrix.container_r10k }}
            WEBHOOK_GO_VERSION=${{ matrix.source_webhook_go }}
          push: false
          platforms: linux/${{ matrix.platform }}

      - name: Scan image with Anchore Grype
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: 'ci/r10k-webhook:${{ github.sha }}'
          fail-build: false

      - name: Inspect action SARIF report
        run: jq . ${{ steps.scan.outputs.sarif }}

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
